# Generated by Django 5.0.4 on 2024-05-23 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimAI', '0002_mimodelo_usuario_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mimodelo',
            name='usuario_creacion',
        ),
    ]
